import type { ProjectListing, ServiceListing } from "../_types";

export const mockProjects: ProjectListing[] = [
  {
    id: "p1",
    name: "PayFácil",
    description: "Plataforma de pagamentos parcelados para MEIs sem burocracia bancária.",
    category: "Fintech",
    stage: "MVP",
    score: 82,
    teamSize: 3,
    price: "R$ 45.000",
    tags: ["Fintech", "B2B", "SaaS"],
  },
  {
    id: "p2",
    name: "MedConnect",
    description: "Marketplace de teleconsultas especializadas com IA de triagem.",
    category: "Healthtech",
    stage: "Tração",
    score: 91,
    teamSize: 5,
    price: "Negociável",
    tags: ["Saúde", "IA", "B2C"],
  },
  {
    id: "p3",
    name: "AgroScore",
    description: "Análise de crédito rural baseada em dados satelitais e clima.",
    category: "Agritech",
    stage: "Ideia",
    score: 67,
    teamSize: 2,
    price: "A combinar",
    tags: ["Agro", "Crédito", "IA"],
  },
  {
    id: "p4",
    name: "SkillPath",
    description: "LMS com trilhas personalizadas por IA para requalificação profissional.",
    category: "Edtech",
    stage: "MVP",
    score: 75,
    teamSize: 4,
    price: "R$ 30.000",
    tags: ["Educação", "IA", "B2B"],
  },
  {
    id: "p5",
    name: "StoreMind",
    description: "Gestão inteligente de estoque para pequenos varejistas.",
    category: "SaaS",
    stage: "Tração",
    score: 88,
    teamSize: 3,
    price: "R$ 60.000",
    tags: ["Varejo", "SaaS", "B2B"],
  },
  {
    id: "p6",
    name: "EduKids",
    description: "App de alfabetização gamificada para crianças de 4-8 anos.",
    category: "Edtech",
    stage: "Ideia",
    score: 61,
    teamSize: 2,
    price: "Negociável",
    tags: ["Educação", "Mobile", "B2C"],
  },
];

export const mockServices: ServiceListing[] = [
  {
    id: "s1",
    name: "Ana Ribeiro",
    specialty: "UX/UI",
    bio: "Designer com 6 anos em produtos digitais. Especialista em SaaS B2B.",
    skills: ["Figma", "Design System", "Prototipagem", "Research"],
    rate: "R$ 150/h",
    availability: "Disponível",
    rating: 4.9,
    reviewCount: 34,
    initials: "AR",
    avatarColor: "bg-purple-500",
  },
  {
    id: "s2",
    name: "Lucas Mendes",
    specialty: "Frontend",
    bio: "Desenvolvedor React/Next.js com foco em performance e acessibilidade.",
    skills: ["React", "Next.js", "TypeScript", "Tailwind"],
    rate: "R$ 120/h",
    availability: "Disponível",
    rating: 4.8,
    reviewCount: 21,
    initials: "LM",
    avatarColor: "bg-cyan-500",
  },
  {
    id: "s3",
    name: "Carla Souza",
    specialty: "Marketing",
    bio: "Growth hacker com track record em startups de Série A.",
    skills: ["Growth", "SEO", "Paid Ads", "CRO"],
    rate: "R$ 130/h",
    availability: "Ocupado",
    rating: 4.7,
    reviewCount: 18,
    initials: "CS",
    avatarColor: "bg-orange-500",
  },
  {
    id: "s4",
    name: "Rafael Costa",
    specialty: "Backend",
    bio: "Engenheiro de software especialista em APIs escaláveis e microsserviços.",
    skills: ["Node.js", "Go", "PostgreSQL", "AWS"],
    rate: "R$ 140/h",
    availability: "Disponível",
    rating: 4.9,
    reviewCount: 27,
    initials: "RC",
    avatarColor: "bg-green-500",
  },
  {
    id: "s5",
    name: "Dra. Juliana Lima",
    specialty: "Jurídico",
    bio: "Advogada especialista em startups: contratos, LGPD e captação.",
    skills: ["LGPD", "Contratos", "IP", "Investimento"],
    rate: "Sob consulta",
    availability: "Disponível",
    rating: 5.0,
    reviewCount: 12,
    initials: "JL",
    avatarColor: "bg-blue-500",
  },
  {
    id: "s6",
    name: "Bruno Ferreira",
    specialty: "Mentoria",
    bio: "Fundador 3x com exits. Mentor de startups em fase de validação.",
    skills: ["Pitch", "Estratégia", "Captação", "Produto"],
    rate: "R$ 200/h",
    availability: "Em breve",
    rating: 4.8,
    reviewCount: 9,
    initials: "BF",
    avatarColor: "bg-rose-500",
  },
];
